FROM python:3.13.11-slim

RUN pip install awslambdaric

ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/local/bin/aws-lambda-rie
RUN chmod +x /usr/local/bin/aws-lambda-rie

COPY main.py .

ENTRYPOINT ["/bin/sh", "-c", "if [ -z \"${AWS_LAMBDA_RUNTIME_API}\" ]; then exec /usr/local/bin/aws-lambda-rie python -m awslambdaric \"$@\"; else exec python -m awslambdaric \"$@\"; fi", "--"]
CMD ["main.lambda_handler"]